services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18.19.0
    envVars:
      - key: NODE_ENV
        value: production